---
- name: configure central log server
  hosts: central
  vars_files:
    - vars.yml
  tasks:
  - name: create volume group
    lvg: vg={{ vg_name }} pvs={{ log_disk }} state=present
  - name: create logical volume
    #shrink=False not supported until 2.2 and we have 2.1
    #lvol: vg={{ vg_name }} lv={{ lv_name }} size={{ lv_size }} shrink=False
    lvol: vg={{ vg_name }} lv={{ lv_name }} size={{ lv_size }}
  - name: create file system
    filesystem: fstype=xfs dev=/dev/{{ vg_name }}/{{lv_name}}
  - name: mount file system
    mount: name={{ mount_point }} src=/dev/{{ vg_name }}/{{ lv_name }} fstype=xfs state=mounted
  - name: create default selinux context for mount point
    #sefcontext not available until 2.2.
    #sefcontext: target='/cf_logs(/.*)?' setype=var_log_t state=present
    command: /usr/sbin/semanage fcontext -a -t var_log_t '{{ mount_point }}(/.*)?'
  - name: set selinux context for mount point
    command: /usr/sbin/restorecon -FR {{ mount_point }}
  - name: open firewall for rsyslog connections on central
    firewalld: port={{ tcp_port }}/tcp permanent=true immediate=true state=enabled
  - name: create central rsyslog config file
    template: src=templates/10-cloudforms-central.conf.j2 dest=/etc/rsyslog.d/10-cloudforms-central.conf owner=root group=root mode=0644
  - name: create input rsyslog config file
    template: src=templates/11-cloudforms-input.conf.j2 dest=/etc/rsyslog.d/11-cloudforms-input.conf owner=root group=root mode=0644
  - name: configure logrotate to rotate the central logs
    template: src=templates/cf_centralized_logs.conf.j2 dest=/etc/logrotate.d/cf_centralized_logs.conf owner=root group=root mode=0644
  - name: add restart of rsyslog to logrotate miq_logs.conf
    lineinfile: dest=/etc/logrotate.d/miq_logs.conf regexp='/sbin/service rsyslog restart.*$' insertafter='/sbin/service httpd reload.*$' line='    /sbin/service rsyslog restart > /dev/null 2>&1 || true'
  - name: enable and restart rsyslog
    service: name=rsyslog enabled=yes state=restarted

- name: configure remote appliances
  hosts: remotes
  vars_files:
    - vars.yml
  tasks:
  - name: create /etc/hosts entry for central
    lineinfile: dest=/etc/hosts regexp='cf_loghost$' line='{{ central_ip }} cf_loghost'
  - name: create forward rsyslog config file
    template: src=templates/10-cloudforms-forward.conf.j2 dest=/etc/rsyslog.d/10-cloudforms-forward.conf owner=root group=root mode=0644
  - name: create input rsyslog config file
    template: src=templates/11-cloudforms-input.conf.j2 dest=/etc/rsyslog.d/11-cloudforms-input.conf owner=root group=root mode=0644
  - name: add restart of rsyslog to logrotate miq_logs.conf
    lineinfile: dest=/etc/logrotate.d/miq_logs.conf regexp='/sbin/service rsyslog restart.*$' insertafter='/sbin/service httpd reload.*$' line='    /sbin/service rsyslog restart > /dev/null 2>&1 || true'
  - name: enable and restart rsyslog
    service: name=rsyslog enabled=yes state=restarted
